name: Django CI

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests with Coverage
      env:
        DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        DJANGO_SETTINGS_MODULE: oc_lettings_site.settings.test
      run: |
        pytest --cov=. --cov-fail-under=80
    - name: Linting with Flake
      run: |     
        flake8
